### ISSUE TITLE
User Interface: Simple and Advanced

### ISSUE THREAD

**Issue by ZircXes** [phillyfan1138/option_dashboard#11]
Consider allowing users a choice between simple / advanced or manual / semi-automatic.

**Comment by phillyfan1138** [comment]
I like this idea a lot.  @thomasnguyen704, thoughts?

**Comment by phillyfan1138** [comment]
I think we have decided to go with several different "pages" for each "type" of option...eg BS, Heston, CGMY, variance gamma, etc.

**Comment by ZircXes** [comment]
I like the idea of "hiding" the underlying mechanics but giving them the opportunity to tune the advanced parameters in full. More along the lines of "Standard" and "Advanced"


  *   In Advanced, all options are available (but grouped logically).
  *   In Standard, your "page" or "tab" or "view" is specific to a methodology or type.

Advanced is technically "built" so makes sense to translate to the pages for the "standard" view.

Chris


________________________________

**Comment by phillyfan1138** [comment]
Ah makes sense.  So in "basic" you get the option of "BS", "variance gamma", "heston", etc; while in advanced you have full control?
