### ISSUE TITLE
Help Option

### ISSUE THREAD

**Issue by ZircXes** [phillyfan1138/option_dashboard#12]
A simple reference with definitions and references would be helpful for documentation. Example: Quantitative group uses this tool and provides link to a team-member who is unfamiliar with the methodologies for option pricing and only knows about BSM; this would allow them to quickly understand the definitions and, if interested, follow-up on reference material similar to a Wiki.

**Comment by phillyfan1138** [comment]
I just pushed a PR, @ZircXes @thomasnguyen704  let me know what you think
