### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by ZircXes** [phillyfan1138/option_dashboard#13]
What about allowing a benchmark between the methodologies here and:

Black-Scholes
Market values

**Comment by phillyfan1138** [comment]
I want to get some more opinions on this...the implied volatility is essentially a benchmark to Black-Scholes.  @ZircXes @atbridge @thomasnguyen704

**Comment by phillyfan1138** [comment]
I've just committed https://github.com/phillyfan1138/option_dashboard/commit/88ccc96990138047fca27b82081114a9e199dc3b which has the BS model as a special case of the model.  C=0, v0=1, vol of vol=0

![image](https://user-images.githubusercontent.com/6961410/34469294-8275c86c-eee1-11e7-930a-a54a90db9ded.png)
