### ISSUE TITLE
Greeks

### ISSUE THREAD

**Issue by ZircXes** [phillyfan1138/option_dashboard#14]
For specified inputs, can the model output the Greeks?

Commonly used in the markets, risk management, and regulatory reviews.

**Comment by phillyfan1138** [comment]
For FSTS: [greeks](http://individual.utoronto.ca/vsurkov/presentations/efficient_fft_computation_option_greeks_09.pdf)

For Fang-Oost:
page 9 of [fang oosterlee](http://ta.twi.tudelft.nl/mf/users/oosterle/oosterlee/COS.pdf)

**Comment by phillyfan1138** [comment]
I've updated the [FFTOptionPricing](https://github.com/phillyfan1138/FFTOptionPricing) library to include delta for both FSTS and Fang-Oost

**Comment by phillyfan1138** [comment]
Just updated [levy functions](https://github.com/phillyfan1138/levy-functions) and pushed to aws.

**Comment by phillyfan1138** [comment]
The theta will actually be fairly complicated due to the discount factor (of all things...).  I wonder what the greeks that option traders actually care about are...is it more important to get gamma or theta?  For example.

**Comment by phillyfan1138** [comment]
Ok, I figured out the discount factor.  See https://github.com/phillyfan1138/FFTOptionPricing for the latest updates.  However, theta will ONLY WORK when NOT USING stochastic volatility.

**Comment by phillyfan1138** [comment]
FYI, feel free to reopen..this hasn't been incorporated into the GUI yet.

**Comment by phillyfan1138** [comment]
Reopening since we need to add some GUI for this
