### ISSUE TITLE
Allow for Calibration

### ISSUE THREAD

**Issue by ZircXes** [phillyfan1138/option_dashboard#15]
Similar to Reverse Stress Test -- Can a user also specify market values and then use historical correlations to 'calibrate' the inputs to markets or create calibration factors? 

Calibration ties to OCC guidance on Risk Management of Financial Derivatives.

**Comment by phillyfan1138** [comment]
Aren't most options marked to market?  Would fixing [issue 8](https://github.com/phillyfan1138/option_dashboard/issues/8) fix this?

**Comment by ZircXes** [comment]
Calibrate model parameters --> Suggested method for non-analytical derivatives is Nelder-Mead.
