### ISSUE TITLE
Extract Data in CSV, TSV, or XLSX

### ISSUE THREAD

**Issue by ZircXes** [phillyfan1138/option_dashboard#21]
Recommended enhancement: Allow user to download results in a simple text file for further analysis.

**Comment by phillyfan1138** [comment]
The API can handle raw data requests.  My initial reaction is to not do this as one of my goals is to "google-ify" finance and try to get away from ad-hoc analysis in Excel.  Would love other opinions though.

**Comment by phillyfan1138** [comment]
So I wonder if instead of a "download to csv" we can instead output the actual parameters used in the REST call.  That way you can simply do a post request against the api and get the data in a (user friendly) json format.
