### ISSUE TITLE
Screen Refresh

### ISSUE THREAD

**Issue by ZircXes** [phillyfan1138/option_dashboard#56]
Once the page loads, if you refresh the website you get a 404 error unless you remove /price.

**Comment by ZircXes** [comment]
Known issue with GitHub hosted pages which do not support HTML5 Push-State / React-Router from Client-Side.

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#serving-apps-with-client-side-routing

> GitHub Pages doesn’t support routers that use the HTML5 pushState history API under the hood (for example, React Router using browserHistory). This is because when there is a fresh page load for a url like http://user.github.io/todomvc/todos/42, where /todos/42 is a frontend route, the GitHub Pages server returns 404 because it knows nothing of /todos/42.

**Comment by phillyfan1138** [comment]
Yeah the hash router is ugly compared to the browser router.  It wouldn't take much to modify it though.

@ZircXes @atbridge @thomasnguyen704 what do you think?  Worth modifying?

**Comment by phillyfan1138** [comment]
I've added a hash router for a while now...Not sure why I haven't closed this issue.
