### ISSUE TITLE
Inputs are drop-downs instead of a text-box with data validation.

### ISSUE THREAD

**Issue by ZircXes** [phillyfan1138/option_dashboard#58]
Inputs are drop-downs instead of a text-box with data validation.

**Comment by phillyfan1138** [comment]
The more I think about this...the more I think this is necessary.  Especially keeping everything in sync once calibration is added.

However, it wont be trivial to add text boxes with validation.

**Comment by ZircXes** [comment]
Yeah, in order to calibrate, we would need to have specific daycounts, and the user would select the volatility based on the daycount convention.

**Comment by phillyfan1138** [comment]
If we want to get into day count conventions we are going to get into some interesting territory.  The open source Quantlib spends what appears to be the majority of its code on timing issues.

**Comment by ZircXes** [comment]
I think we can avoid daycount conversions by allowing an input for T and volatility; however, for calibration purposes, the user has to consistently apply T and volatility.
