### ISSUE TITLE
Feature Request -- Reverse Stress Test

### ISSUE THREAD

**Issue by ZircXes** [phillyfan1138/option_dashboard#7]
Would be interesting to setup a reverse stress test (Target a VaR, ES, or Price based on conditions) and then stressing each input to determine what would break to that level.

Method 1: Independent, single variable approach.
Method 2: Correlated market movement (Scenario Probability approach).

**Comment by phillyfan1138** [comment]
What part would be stressed?  Currently the dashboard is using a single stock/option combination.

**Comment by phillyfan1138** [comment]
I believe this is out of scope for this dashboard...if you disagree feel free to reopen
